# To use the nginx alpine web server
FROM nginx:alpine

# Copy content of current directory to root directory of our container
COPY . /usr/share/nginx/html



# To use the apache web server
# FROM apache
# COPY . /var/www/html